[2023-12-26T07:47:29.359+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: potential_customers_process.create_customers_table __airflow_temporary_run_2023-12-26T07:47:26.769021+00:00__ [queued]>
[2023-12-26T07:47:29.376+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: potential_customers_process.create_customers_table __airflow_temporary_run_2023-12-26T07:47:26.769021+00:00__ [queued]>
[2023-12-26T07:47:29.377+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-26T07:47:29.377+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-12-26T07:47:29.377+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-26T07:47:29.391+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_customers_table> on 2022-01-01 00:00:00+00:00
[2023-12-26T07:47:29.398+0000] {standard_task_runner.py:55} INFO - Started process 33703 to run task
[2023-12-26T07:47:29.401+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'potential_customers_process', 'create_customers_table', '__***_temporary_run_2023-12-26T07:47:26.769021+00:00__', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/potential_customers_process.py', '--cfg-path', '/tmp/tmp8d58yq1h']
[2023-12-26T07:47:29.403+0000] {standard_task_runner.py:83} INFO - Job 92: Subtask create_customers_table
[2023-12-26T07:47:29.447+0000] {task_command.py:376} INFO - Running <TaskInstance: potential_customers_process.create_customers_table __airflow_temporary_run_2023-12-26T07:47:26.769021+00:00__ [running]> on host 2d20203c1be8
[2023-12-26T07:47:29.512+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=potential_customers_process
AIRFLOW_CTX_TASK_ID=create_customers_table
AIRFLOW_CTX_EXECUTION_DATE=2022-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=__***_temporary_run_2023-12-26T07:47:26.769021+00:00__
[2023-12-26T07:47:29.520+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-12-26T07:47:29.523+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS customers (
                fullname TEXT NOT NULL,
                country_code TEXT NOT NULL,
                gender TEXT NOT NULL,
                age INT NOT NULL
            );
        , parameters: None
[2023-12-26T07:47:29.525+0000] {postgres.py:96} INFO - NOTICE:  relation "customers" already exists, skipping

[2023-12-26T07:47:29.532+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=potential_customers_process, task_id=create_customers_table, execution_date=20220101T000000, start_date=20231226T074729, end_date=20231226T074729
[2023-12-26T07:47:29.576+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-12-26T07:47:29.596+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
